version: "2"
services:
  redis:
    image: redis:3.2
    ports:
      - 16379:6379
    volumes:
      - ./storage/redis:/data
  mysql:
    image: mysql:5.7
    command: "--innodb_use_native_aio=0"
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - ./storage/mysql:/var/lib/mysql
